name: gaza_go
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.5+38

environment:
  sdk: '>=2.18.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  dio: ^4.0.4 #https://pub.dev/packages/dio
  get: ^4.6.5 #https://pub.dev/packages/get
  intl: ^0.17.0 #https://pub.dev/packages/intl
  hive: ^2.2.3 #https://pub.dev/packages/hive
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  rxdart: ^0.27.5 #https://pub.dev/packages/rxdart
  lottie: ^1.4.2 #https://pub.dev/packages/lottie
  share_plus: ^4.0.10+1 #https://pub.dev/packages/share_plus
  logger: ^1.1.0 #https://pub.dev/packages/logger
  url_launcher: ^6.1.5 #https://pub.dev/packages/url_launcher
  connectivity_plus: ^3.0.2 #https://pub.dev/packages/connectivity_plus/install
  firebase_core: ^2.4.1 #https://pub.dev/packages/firebase_core
  firebase_auth: ^4.2.5 #https://pub.dev/packages/firebase_auth
  firebase_analytics: ^10.1.0 #https://pub.dev/packages/firebase_analytics/install
  firebase_crashlytics: ^3.0.11 #https://pub.dev/packages/firebase_crashlytics
  firebase_dynamic_links: ^5.0.11 #https://pub.dev/packages/firebase_dynamic_links
  firebase_remote_config: ^3.0.9 #https://pub.dev/packages/firebase_remote_config
  firebase_performance: ^0.9.0+10 #https://pub.dev/packages/firebase_performance
  firebase_app_check: ^0.1.1+8 #https://pub.dev/packages/firebase_app_check
  firebase_in_app_messaging: ^0.7.0+10 #https://pub.dev/packages/firebase_in_app_messaging
  firebase_messaging: ^14.2.1 #https://pub.dev/packages/firebase_messaging
  flutter_svg: ^1.1.4 #https://pub.dev/packages/flutter_svg
  flutter_local_notifications: ^9.9.0 #https://pub.dev/packages/flutter_local_notifications
  package_info_plus: ^1.4.3+1 #https://pub.dev/packages/package_info_plus
  json_annotation: ^4.6.0 #https://pub.dev/packages/json_annotation
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.2
  image_picker: ^0.8.5+3
  flutter_gallery_assets: ^1.0.2
  flutter_flavorizr: ^2.1.4
  google_sign_in: ^5.4.1
  sign_in_with_apple: ^4.1.0
  uuid: ^3.0.6
  flutter_naver_map:
    git: https://github.com/wnsgh78b/flutter_naver_map.git
  geolocator: ^9.0.2
  pedometer: ^3.0.0
  permission_handler: ^10.0.2
  flutter_svg_provider: ^1.0.3
  percent_indicator: ^4.2.2
  infinite_scroll_pagination: ^3.2.0
  table_calendar: ^3.0.7
  modal_bottom_sheet: ^3.0.0-pre
  smooth_page_indicator: ^1.0.0+2
  fluttertoast: ^8.0.9
  custom_rounded_rectangle_border: ^0.2.0-nullsafety.0
  another_xlider: ^1.1.2
  animated_flip_counter: ^0.2.5
  health: ^4.1.1
  expandable_bottom_sheet: ^1.1.1+1

  simple_animations: ^5.0.0+2
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.13

  carousel_slider: ^4.1.1
  flutter_screenutil: ^5.6.0
  throttling: ^1.0.0
  flutter_inappwebview: ^6.0.0-beta.22
  google_mobile_ads: ^2.3.0
  path_provider: ^2.0.11
  advertising_id: 2.3.0
  device_info_plus: ^8.0.0
  cloud_firestore: ^4.3.1
  internet_connection_checker: ^1.0.0+1

  solana: ^0.27.0
  solana_web3: ^0.0.4
  encrypt: ^5.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  json_serializable: ^6.3.1 #https://pub.dev/packages/json_serializable
  build_runner: ^2.2.0 #https://pub.dev/packages/build_runner
  geolocator_android: 4.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

dependency_overrides:
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/common/
    - assets/images/login/
    - assets/images/activity/
    - assets/images/archive/
    - assets/images/leaderboard/
    - assets/images/inventory/
    - assets/images/wallet/
    - assets/images/preference/
    - assets/images/permissions/
    - assets/images/shop/
    - assets/lottie/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 기본 폰트는 프리텐다드로 한다. https://cactus.tistory.com/306
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/pretendard/Pretendard-Black.otf
          weight: 900
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Thin.otf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-Light.otf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.otf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.otf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-Black.otf
          weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "가자고-dev"

      android:
        applicationId: "kr.co.eztechfin.gazaGo.dev"
        firebase:
          config: ".firebase/dev/google-services.json"
      ios:
        bundleId: "kr.co.eztechfin.gazaGo.dev"
        firebase:
          config: ".firebase/dev/GoogleService-Info.plist"
    stage:
      app:
        name: "가자고-stage"
      android:
        applicationId: "kr.co.eztechfin.gazaGo.dev"
        firebase:
          config: ".firebase/dev/google-services.json"
      ios:
        bundleId: "kr.co.eztechfin.gazaGo.dev"
        firebase:
          config: ".firebase/dev/GoogleService-Info.plist"
    prod:
      app:
        name: "가자고"

      android:
        applicationId: "kr.co.eztechfin.gazaGo"
        firebase:
          config: ".firebase/prod/google-services.json"
      ios:
        bundleId: "kr.co.eztechfin.gazaGo"
        firebase:
          config: ".firebase/prod/GoogleService-Info.plist"