// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHmS0LwPeoXpiZqW42qDFZ5iOth-VovAo',
    appId: '1:321889905131:android:945691702c6a0df10a11ae',
    messagingSenderId: '321889905131',
    projectId: 'app-step-prod',
    databaseURL: 'https://app-step-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-step-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0fw8oOZhK1DIRpQMCFaWvBA4D8L-bXIc',
    appId: '1:321889905131:ios:fcd56d852edb7bc40a11ae',
    messagingSenderId: '321889905131',
    projectId: 'app-step-prod',
    databaseURL: 'https://app-step-prod-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-step-prod.firebasestorage.app',
    androidClientId: '321889905131-0rc3j4vaf51g239ruleth269dvhh62s7.apps.googleusercontent.com',
    iosClientId: '321889905131-22r952df5n2g5i3qehb6dgcg5o4188dt.apps.googleusercontent.com',
    iosBundleId: 'kr.co.eztechfin.gazaGo',
  );
}
