import 'package:get/get.dart';
import 'package:gaza_go/constants/enums.dart';
import 'package:gaza_go/constants/routes.dart';
import 'package:gaza_go/platform/models/archive_item_model.dart';

class ArchiveController extends GetxController {
  RxList<ArchiveItemModel> archiveList = RxList.empty();
  Rx<ArchiveItemModel> selectedItem = Rx(ArchiveItemModel(
    id: 1,
    activityType: ActivityType.climbing,
    startTime: '2022.08.12 09:04:34',
    endTime: '2022.08.12 09:55:11',
    startLocation: '만월산',
    startLocationFull: '만월산 등산로 입구',
    acquiredBadge: '만월산 등정 뱃지',
    activityDuration: '02:01:01',
    activityDistance: 4.02,
    stepCount: 50,
    avgSpeed: 4.2,
    highestClimbed: 140.0,
    acquiredGo: 50,
    staminaUsed: 70,
    durabilityConsumed: 10,
  ));

  @override
  void onInit() {
    getArchiveList();
    super.onInit();
  }

  void getArchiveList() {
    archiveList.value = [
      ArchiveItemModel(
        id: 1,
        activityType: ActivityType.climbing,
        startTime: '2022.08.12 09:04:34',
        endTime: '2022.08.12 09:55:11',
        startLocation: '만월산',
        startLocationFull: '만월산 등산로 입구',
        acquiredBadge: '만월산 등정 뱃지',
        activityDuration: '02:01:01',
        activityDistance: 4.02,
        stepCount: 50,
        avgSpeed: 4.2,
        highestClimbed: 140.0,
        acquiredGo: 50,
        staminaUsed: 70,
        durabilityConsumed: 10,
      ),
      ArchiveItemModel(
        id: 1,
        activityType: ActivityType.climbing,
        startTime: '2022.08.12 09:04:34',
        endTime: '2022.08.12 09:55:11',
        startLocation: '만월산',
        startLocationFull: '만월산 등산로 입구',
        acquiredBadge: '만월산 등정 뱃지',
        activityDuration: '02:01:01',
        activityDistance: 4.02,
        stepCount: 50,
        avgSpeed: 4.2,
        highestClimbed: 140.0,
        acquiredGo: 50,
        staminaUsed: 70,
        durabilityConsumed: 10,
      ),
      ArchiveItemModel(
        id: 1,
        activityType: ActivityType.climbing,
        startTime: '2022.08.12 09:04:34',
        endTime: '2022.08.12 09:55:11',
        startLocation: '만월산',
        startLocationFull: '만월산 등산로 입구',
        acquiredBadge: '만월산 등정 뱃지',
        activityDuration: '02:01:01',
        activityDistance: 4.02,
        stepCount: 50,
        avgSpeed: 4.2,
        highestClimbed: 140.0,
        acquiredGo: 50,
        staminaUsed: 70,
        durabilityConsumed: 10,
      ),
      ArchiveItemModel(
        id: 1,
        activityType: ActivityType.climbing,
        startTime: '2022.08.12 09:04:34',
        endTime: '2022.08.12 09:55:11',
        startLocation: '만월산',
        startLocationFull: '만월산 등산로 입구',
        acquiredBadge: '만월산 등정 뱃지',
        activityDuration: '02:01:01',
        activityDistance: 4.02,
        stepCount: 50,
        avgSpeed: 4.2,
        highestClimbed: 140.0,
        acquiredGo: 50,
        staminaUsed: 70,
        durabilityConsumed: 10,
      ),
      ArchiveItemModel(
        id: 1,
        activityType: ActivityType.climbing,
        startTime: '2022.08.12 09:04:34',
        endTime: '2022.08.12 09:55:11',
        startLocation: '만월산',
        startLocationFull: '만월산 등산로 입구',
        acquiredBadge: '만월산 등정 뱃지',
        activityDuration: '02:01:01',
        activityDistance: 4.02,
        stepCount: 50,
        avgSpeed: 4.2,
        highestClimbed: 140.0,
        acquiredGo: 50,
        staminaUsed: 70,
        durabilityConsumed: 10,
      ),
      ArchiveItemModel(
        id: 1,
        activityType: ActivityType.climbing,
        startTime: '2022.08.12 09:04:34',
        endTime: '2022.08.12 09:55:11',
        startLocation: '만월산',
        startLocationFull: '만월산 등산로 입구',
        acquiredBadge: '만월산 등정 뱃지',
        activityDuration: '02:01:01',
        activityDistance: 4.02,
        stepCount: 50,
        avgSpeed: 4.2,
        highestClimbed: 140.0,
        acquiredGo: 50,
        staminaUsed: 70,
        durabilityConsumed: 10,
      ),
      ArchiveItemModel(
        id: 1,
        activityType: ActivityType.climbing,
        startTime: '2022.08.12 09:04:34',
        endTime: '2022.08.12 09:55:11',
        startLocation: '만월산',
        startLocationFull: '만월산 등산로 입구',
        acquiredBadge: '만월산 등정 뱃지',
        activityDuration: '02:01:01',
        activityDistance: 4.02,
        stepCount: 50,
        avgSpeed: 4.2,
        highestClimbed: 140.0,
        acquiredGo: 50,
        staminaUsed: 70,
        durabilityConsumed: 10,
      ),
      ArchiveItemModel(
        id: 1,
        activityType: ActivityType.climbing,
        startTime: '2022.08.12 09:04:34',
        endTime: '2022.08.12 09:55:11',
        startLocation: '만월산',
        startLocationFull: '만월산 등산로 입구',
        acquiredBadge: '만월산 등정 뱃지',
        activityDuration: '02:01:01',
        activityDistance: 4.02,
        stepCount: 50,
        avgSpeed: 4.2,
        highestClimbed: 140.0,
        acquiredGo: 50,
        staminaUsed: 70,
        durabilityConsumed: 10,
      ),
    ];
  }

  void toDetail(int id) {
    selectedItem.value = archiveList.firstWhere((archive) => archive.id == id);
    Get.toNamed(Routes.archiveDetail);
  }
}
