// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:gaza_go/flavors.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => F.appFlavor!.name == Flavor.dev.name || F.appFlavor!.name == Flavor.stage.name
      ? const FirebaseOptions(
          apiKey: 'AIzaSyDMz-7VGwfPTUHcTeJa8C-HL94DsyjELG8',
          appId: '1:232716676384:android:b1fdff92f1a418d06f7b45',
          messagingSenderId: '232716676384',
          projectId: 'app-step-dev',
          storageBucket: 'app-step-dev.appspot.com',
        )
      : const FirebaseOptions(
          apiKey: 'AIzaSyBHmS0LwPeoXpiZqW42qDFZ5iOth-VovAo',
          appId: '1:321889905131:android:32e7185de2c0a9440a11ae',
          messagingSenderId: '321889905131',
          projectId: 'app-step-prod',
          storageBucket: 'app-step-prod.appspot.com',
        );

  static FirebaseOptions get ios => F.appFlavor!.name == Flavor.dev.name || F.appFlavor!.name == Flavor.stage.name
      ? const FirebaseOptions(
          apiKey: 'AIzaSyDFXvYaMdfv-xPxCQpXnD30o66pGmxfKFo',
          appId: '1:232716676384:ios:c851d637fa6d71246f7b45',
          messagingSenderId: '232716676384',
          projectId: 'app-step-dev',
          storageBucket: 'app-step-dev.appspot.com',
          androidClientId: '232716676384-dcu40b5ttfklj1s8d1kocg3cr8i1uaum.apps.googleusercontent.com',
          iosClientId: '232716676384-5iun8ict73an15rbh40patma4rpgmlfh.apps.googleusercontent.com',
          iosBundleId: 'kr.co.eztechfin.gazaGo.dev',
        )
      : const FirebaseOptions(
          apiKey: 'AIzaSyA0fw8oOZhK1DIRpQMCFaWvBA4D8L-bXIc',
          appId: '1:321889905131:ios:fcd56d852edb7bc40a11ae',
          messagingSenderId: '321889905131',
          projectId: 'app-step-prod',
          storageBucket: 'app-step-prod.appspot.com',
          androidClientId: '321889905131-5q4hne8soo1v8lebda6drl4vp9tv8grd.apps.googleusercontent.com',
          iosClientId: '321889905131-22r952df5n2g5i3qehb6dgcg5o4188dt.apps.googleusercontent.com',
          iosBundleId: 'kr.co.eztechfin.gazaGo',
        );
}
